### ISSUE TITLE
Text don't fit to screen when reading on mobile phone

### ISSUE THREAD

**Issue by nick4eva** [grafana/tutorials#100]
I was reading tutorial on mobile phone and observed that text didn't fit mobile phone screen.

![Screenshot_20210114-083508](https://user-images.githubusercontent.com/136439/104553630-ab335e00-5643-11eb-8eac-2673968fa83a.png)

**Comment by marcusolsson** [comment]
We are working on a complete (mobile-friendly) overhaul of the tutorials site. Stay tuned! :)

**Comment by scoren-gl** [comment]
We just launched a new page design today and the mobile issue is resolved.  If you still see anything off, please file a new issue.
