### ISSUE TITLE
doesn't work on ARMv6 Raspberries

### ISSUE THREAD

**Issue by vidmo91** [grafana/tutorials#104]
You should at least inform users about compatibility in this tutorial.

**Comment by marcusolsson** [comment]
We definitely should! Though I'd also like to figure out if we can get it to work on ARMv6 as well

**Comment by vidmo91** [comment]
It works fine. I downloaded ARMv6 from link below and followed other instructions from this tutorial.
https://grafana.com/grafana/download?platform=arm

**Comment by matthewhelmke** [comment]
Closing. Unable to reproduce.
