### ISSUE TITLE
Needs tutorial updates

### ISSUE THREAD

**Issue by MacNale** [grafana/tutorials#105]
Team,

I could not easily follow the 'build datasource' tutorial and build some thing useful. Typically, most of the plugins make some kind of REST apis to the backend.

Could you please add details about example REST API and authentication for completeness in the tutorial? 

thanks,
Mac

**Comment by marcusolsson** [comment]
Thank you for the feedback! 

> I could not easily follow the 'build datasource' tutorial 

Were there steps that were difficult to understand or follow? If so, which ones?

> Typically, most of the plugins make some kind of REST apis to the backend

This is what step 9, [Get data from an external API](https://grafana.com/tutorials/build-a-data-source-plugin/#9) aims to describe. Could you share more details on what you felt was missing?

In the meantime, there's an example of a HTTP-based data source available [here](https://github.com/grafana/grafana-plugin-examples/tree/master/http-datasource) that might help you.

**Comment by MacNale** [comment]
I could not figure out about the - SERVER proxy, how to authenticate with basic auth. Now that you have provided the link, let me see how it goes. 

Thank you for example link.  I wish if tutorial could lead developers to example github link.

**Comment by MacNale** [comment]
I managed to build a datasource plugin using  example provided by @marcusolsson. Closing this issue.
