### ISSUE TITLE
Grafana App Plugin Tutorial question

### ISSUE THREAD

**Issue by stonepreston** [grafana/tutorials#109]
Hey,

I took a look at the [grafana starter app ](https://github.com/grafana/grafana-starter-app) and the [work-in-progress tutorial ](https://github.com/grafana/tutorials/blob/master/content/tutorials/build-an-app-plugin.md) and was able to build a simple app plugin. Thank you for providing those! There is currently not much documentation on app plugins and I had one question about them. Is it possible to create a page that also displays a dashboard? Currently I've got a page with things like input forms and text, I would like to display a dashboard under all that as well (instead of having to have the user navigate to the dashboard itself). Is that possible? I know it's possible to use an iframe to embed a dashboard but that is not what I am looking for.

**Comment by matthewhelmke** [comment]
Apologies. It's been a long time since you asked your question. You are likely to have more luck getting a response (if you still have need) in either the Grafana [slack](https://grafana.slack.com/) or the [forums](https://community.grafana.com/).

Closing as stale.
