### ISSUE TITLE
Problem with tutorial for building a datasource plugin with backend

### ISSUE THREAD

**Issue by briangann** [grafana/tutorials#110]
During the tutorial in <https://grafana.com/tutorials/build-a-data-source-backend-plugin/>, the step after

```
❯ go get -u github.com/grafana/grafana-plugin-sdk-go
go get: upgraded github.com/grafana/grafana-plugin-sdk-go v0.86.0 => v0.88.0
```

then `mage -v` produces this output:

```
../../../../pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.88.0/build/common_unix.go:15:2: missing go.sum entry for module providing package golang.org/x/sys/unix; to add:
	go mod download golang.org/x/sys
Error: error compiling magefiles
```

running `go mod download golang.org/x/sys` results in more error output.

Instead of doing this, before the `mage -v` just run `go mod tidy` and the dependencies get fixed in `go.mod`.  After running that, `mage -v` will build the backend correctly.

**Comment by matthewhelmke** [comment]
This was fixed some time ago, but the issue was never closed. Closing now.
