### ISSUE TITLE
Add how to clean up envs to all tutorials

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/tutorials#121]
Enhance the customer experience with running tutorials by adding how to clean up the environment created. There are generally a set of Docker containers left running.  That could be a problem for a tutorial user when that user attempts to create/use other Docker containers for other things.  It is resource usage and there might be port conflicts.

Generally, if the environment is created with 
  docker-compose up
then the way to break down and clean up is with
  docker-compose down -v

**Comment by matthewhelmke** [comment]
All tutorials have been checked and the instructions have been added where needed.
