### ISSUE TITLE
State where commands are run

### ISSUE THREAD

**Issue by KMiller-Grafana** [grafana/tutorials#122]
An enhancement to all the tutorials would be to explicitly state where the tutorial user runs the commands given in the tutorial.  

For example, in the Grafana Fundamentals tutorial, the section called Set Up the Sample Application, make it explicit that all the commands given are shell/terminal commands. Instead of
> In this step, you’ll set up the sample application, as well as supporting services, such as Prometheus and Loki.
the tutorial might say 
> In this step, you’ll set up the sample application, as well as supporting services, such as Prometheus and Loki by issuing shell commands.

Perhaps add similar wording in each spot within each tutorial that gives shell commands without stating that they are shell commands.

**Comment by matthewhelmke** [comment]
This has been considered and deemed unnecessary for our target audience.
