### ISSUE TITLE
Raspberry Pi Grafana Installation Issue

### ISSUE THREAD

**Issue by Coderakid01** [grafana/tutorials#136]
![efrf](https://user-images.githubusercontent.com/40556833/126451482-34686ee8-67b2-4d50-8fcf-89f0ae700c9d.PNG)

Hi, I tried to install Grafana on my RPI but it appears there's an error, is there any solution to be suggest? Yes I'm doing the installation from the official tutorial from this link https://grafana.com/tutorials/install-grafana-on-raspberry-pi/

**Comment by matthewhelmke** [comment]
This shouldn't be failing. I'm looking into this within Grafana Labs. We'll get back to you when we have more info.

**Comment by matthewhelmke** [comment]
It looks like this is the result of this issue: https://github.com/grafana/grafana/issues/35273

I'm going to close here as this is not a bug with the tutorial, but rather the software repo. Please follow the linked issue and feel free to comment there.
