### ISSUE TITLE
Documentation - Explore your metrics

### ISSUE THREAD

**Issue by VK1IAN** [grafana/tutorials#155]
I followed https://grafana.com/tutorials/grafana-fundamentals/?utm_source=grafana_gettingstarted under the "Explore your metrics" section, I get as far as "In the side bar, click the Explore (compass rose) icon" (yet another reason why a well structured text menu is far better that universally ambiguous icons), I don't see "Enter a PromQL query" anywhere on the page.
This page was updated on November 11, 2021 and I'm using v8.3.3 (30bb7a93ca) installed via IOTstack.
I have to say Grafana is not very intuitive to use. I am very familiar with Cacti, so editing graphs, etc is not new to me. I can't even get a graph in a panel to stick; I do all the config and can't find a way to save it.
I clearly don't think like your developers; better documentation would be a good start.

**Comment by SethFalco** [comment]
Just wanted to report the "Enter a PromQL query" issue as well.
In both the version of Grafana used in this tutorial, and the latest version, the text box to input PromQL doesn't state "Enter a PromQL query", it's blank.

Either the tutorial should have that text removed, or Grafana should add placeholder text like "Enter a PromQL query…" in the Explore page when Prometheus is the selected source.

**Comment by SethFalco** [comment]
I tried to see if I could add this in myself, but I think there's a bug in Monaco that's preventing it from working correctly. 🤔 

Filed here, once this is resolved, I can make a PR since it would be nice if the field actually said: "Enter a PromQL query".

https://github.com/microsoft/monaco-editor/issues/3220
