### ISSUE TITLE
Alerting Section of Tutorial Needs Updating

### ISSUE THREAD

**Issue by rthomasson** [grafana/tutorials#173]
The Alerting section of the tutorial refers to Notification Channels but in the version of Grafana used in the tutorial, they're Contact Points.

**Comment by peterholmberg** [comment]
Hello @rthomasson, thank you for reporting this. We will update or possibly create a new tutorial to cover Grafana 8 alerting.

**Comment by jtheory** [comment]
https://github.com/grafana/tutorials/pull/167 handles removing the obsolete parts -- the next step will be writing a new tutorial for Unified Alerting.

**Comment by zuchka** [comment]
I've merged the above PR, which removes the old alerting section from the tutorial. I'll link a 2nd PR later this week with updated Alerting steps

**Comment by zuchka** [comment]
FYI: https://github.com/grafana/tutorials/pull/178
