### ISSUE TITLE
Can't find Notification Channel

### ISSUE THREAD

**Issue by borjagomez** [grafana/tutorials#175]
Can't find the Notification Channel option under the Alerting menu.

**Comment by peterholmberg** [comment]
Yes, the tutorial is currently covering legacy alerting (pre Grafana 8) and would need to be updated for Unified alerting.

**Comment by peterholmberg** [comment]
Fixing this is a part of https://github.com/grafana/tutorials/issues/173 and will close this issue and track it in #173. Thanks for reporting nonetheless
