### ISSUE TITLE
Issue with Fundanmentals training App_1 & db_1 does not work

### ISSUE THREAD

**Issue by rjgarrow** [grafana/tutorials#182]
HI all,

I hope someone can help, I am trying to do the training. This is running on a Raspberry Pi4 8GB 32GBstorage. I followed the install and rebuilt my pi like three times and still each time when I run docker-compose ps after the build it completed tutorial-environment_app_1 and tutorial-environment_db_1 in the state it says Exit 2 on app_1 and Exit 1 on Db_1. I know it trying to run Alpine and I think this might be the issue. Can anyone make any suggestions on this??

**Comment by zuchka** [comment]
yes I don't think that docker compose file is optimized to run on the Pi's platform
