### ISSUE TITLE
docker-compose prometheus volume error 

### ISSUE THREAD

**Issue by hrvwnd** [grafana/tutorials#33]
It seems there an error when copying over the prometheus/prometheus.yml file to the docker container /etc/... as the prometheus container goes down immediately after docker-compose up -d 

Error message shown in docker-compose logs:

`prometheus_1  | level=error ts=2020-04-09T10:48:34.214Z caller=main.go:740 err="error loading config from \"/etc/prometheus/prometheus.yml\": couldn't load configuration (--config.file=\"/etc/prometheus/prometheus.yml\"): open /etc/prometheus/prometheus.yml: no such file or directory"`

**Comment by marcusolsson** [comment]
Thank for sharing. I'm unfortunately unable to reproduce this. Could you share some more information on the system your running on, such as operating system and Docker version?

**Comment by hrvwnd** [comment]
Hi, I'm using:
Docker version 19.03.8, build afacb8b7f0 (i've just seen on the github README that version should be Docker >= 2.1.0.3)  
Microsoft Windows [Version 10.0.17763.107]
- I followed https://grafana.com/tutorials/grafana-fundamentals/#

**Comment by marcusolsson** [comment]
Docker version should be fine. I went ahead and tested in on a Windows machine, and didn't run into any issues. 

I'll try to explore this a bit more. If you end up figuring something out, please update this issue so that I can update the tutorial with some tips on how to troubleshoot.

**Comment by hrvwnd** [comment]
Thanks I'll keep you updated too.  A collegue of mine is having the same issue and error so theres some repeatablity on the machines we are using. Let me know if I can give you any more information.

Something I didn't mention was that we're using wsl ubuntu v1.

**Comment by hrvwnd** [comment]
Hi, so the problem seemed to be due to the mount C: drive (/mnt/c) as the files were not being copied over in the volume. Instead of trying to copy the prometheus.yml from my wsl directories i directed it to somewhere on the windows c mount. I changed the docker-compose.yml line 15 to
`- /c/Users/<myuser>/Downloads/tutorial-environment-master/prometheus/:/etc/prometheus/`

I used the command below to test which files i could mount and from where.
`docker run --rm -it -v "/foo/:/tmp/test" -w /tmp/test busybox /bin/sh -c "pwd; ls -la"`
