### ISSUE TITLE
Exit 1 message when creating tutorial-envoironment_loki_1

### ISSUE THREAD

**Issue by EduSpencer** [grafana/tutorials#37]
Hi Team,

I followed the Grafana fundamentals tutorial (using Docker for Desktop for macOS) and am getting an exit 1 message on the loki tutorial environment.

```
$ docker-compose ps
              Name                             Command               State            Ports         
----------------------------------------------------------------------------------------------------
tutorial-environment_app_1          /bin/sh -c /app http://db  ...   Up       0.0.0.0:8081->80/tcp  
tutorial-environment_db_1           /db                                            Up       0.0.0.0:8082->80/tcp  
tutorial-environment_grafana_1      /run.sh                                  Up       0.0.0.0:3000->3000/tcp
tutorial-environment_loki_1         /usr/bin/loki -config.file ...      Exit 1                         
tutorial-environment_prometheus_1   /bin/prometheus --config.f ...   Up       0.0.0.0:9090->9090/tcp
tutorial-environment_promtail_1     /usr/bin/promtail -config. ...   Up  
```

The environment is not running and I get the following from the docker logs:
failed parsing config: /etc/loki/local-config.yaml: not a valid duration string: "0"

Not sure if there is something I am missing here or an issue with the image? Anyway, wanted to post here in case it is an issue that other users are seeing.

Thanks,

Edward.

**Comment by marcusolsson** [comment]
Was able to reproduce. Seems to be an error in the latest Loki image. I've changed from `latest` to using fixed versions for Loki and promtail. Thanks for the heads-up!
