### ISSUE TITLE
Build a panel plugin with D3.js  errors

### ISSUE THREAD

**Issue by GokulSNarayan** [grafana/tutorials#45]
Missing return statement in draw function in Build a panel plugin with D3.js tutorial and the tutorial runs into setPanelOptions error at step 4.
 Grafana Version: 6.7.3 (a04ef6cefc)

**Comment by marcusolsson** [comment]
Thank you for reporting this. I'll update the tutorial during the day.

**Comment by marcusolsson** [comment]
Updated version is now published. Note that you need the master build of Grafana to complete the tutorial, as the APIs used in the tutorial haven't officially been released yet.

https://grafana.com/tutorials/build-a-panel-plugin-with-d3/

**Comment by GokulSNarayan** [comment]
Wow... that was quick....thanks for updating it. And regarding upgrading to master branch, will it cause my other plugins to break. Could you provide me the steps to upgrade as I installed Grafana using apt in Ubuntu 20.04.

**Comment by marcusolsson** [comment]
Grafana 7.0 is still in beta, and although we encourage people to use it, we don't recommend using it for production until the official release.

We'll update the apt repository as soon as we release Grafana 7.0 later this month, but if you want to make sure that your plugins still work before upgrading, consider using the [Docker method](https://grafana.com/tutorials/build-a-panel-plugin-with-d3/#2):

You can use the `grafana/grafana:master` image to get the latest version:

```
docker run -d -p 3000:3000 -v $PLUGIN_DIRECTORY:/var/lib/grafana/plugins --name=grafana grafana/grafana:master
```

Thank you for trying out the tutorial. Let me know if you run into any other issues!

**Comment by GokulSNarayan** [comment]
I got this issue when I tried to install the grafana/tookit
npx "@grafana/toolkit"@canary plugin:create liquid-fill
![Screenshot from 2020-05-06 11-13-57](https://user-images.githubusercontent.com/44142590/81141599-d6c95900-8f8a-11ea-8d41-731ee69efc5c.png)

**Comment by marcusolsson** [comment]
Does it work if you run?:

```
npx "@grafana/toolkit"@next plugin:create liquid-fill
```

**Comment by GokulSNarayan** [comment]
Actually I tried with just `npx @grafana/toolkit plugin:create liquid-fill  ` and it worked. Does adding next provide the latest version of it ?

**Comment by marcusolsson** [comment]
`npx @grafana/toolkit plugin:create` uses the stable version, which might not have the required dependencies yet.

`npx "@grafana/toolkit"@next plugin:create liquid-fill` gives you the latest version.

Sorry about the issues you're having. This will be easier once Grafana 7.0 is officially released.

**Comment by GokulSNarayan** [comment]
Ok...
