### ISSUE TITLE
Build a data source plugin tutorial - Step 8 

### ISSUE THREAD

**Issue by jssm** [grafana/tutorials#52]
[Tutorial link](https://grafana.com/tutorials/build-a-data-source-plugin/#8)

On step 8, since the variable resolution is defined as a number, a conversion from string is missing on the onResolutionChange method. And the fact that is defined as a "number?" on the types.ts file, it also gives problems when using it on the DataSource.ts file (I just took the ? since a default value of 1000 is given on the FormField of the ConfigEditor if nothing is set).

Is it possible to revise these points? Pretty please :)

Thank you very much and kind regards

**Comment by marcusolsson** [comment]
Thank you! Looking into this now.

**Comment by marcusolsson** [comment]
@jssm I've published the fixes. Let me know if you're still experiencing any issues with the tutorials!

**Comment by jssm** [comment]
Thank you @marcusolsson, it makes much more sense now :)
