### ISSUE TITLE
Create a new plugin tutorial: grafana/toolkit error

### ISSUE THREAD

**Issue by LRitchie489** [grafana/tutorials#61]
I'm working through the tutorials and the `npx @grafana/toolkit plugin:create my-plugin` command fails with `Unexpected token {`

I'm on ubuntu 18.0.4 with freshly installed npm, yarn, and npx, installed Grafana 7.0.1 yesterday.

**Comment by marcusolsson** [comment]
I can't seem to reproduce this unfortunately. Is that the only output you're getting? In that case it might be some issues with you npm installation. Does it work with packages other than grafana/toolkit?

**Comment by bonnydeal** [comment]
I had the same issue on amazon linux 2.

Solution was to uninstall node and npm and re-install using the latest version from 
https://nodejs.org/en/download/

**Comment by marcusolsson** [comment]
The grafana-toolkit currently requires Node 12. You may see this message if you're running an unsupported Node version.

I've updated the tutorials with the version requirement. Closing this for now, but will reopen if the issue occurs on Node 12.
