### ISSUE TITLE
Sample app returns no data

### ISSUE THREAD

**Issue by ctliv** [grafana/tutorials#63]
Environment:
- Windows 10 version 1709
- Docker Engine (community) version 19.03.8

Just executed:
```
git clone https://github.com/grafana/tutorial-environment.git
cd tutorial-environment
docker-compose up -d
```
All services are regularly up and running. But:

$ curl http://localhost:8081
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server

Even opening a shell in "grafana_app_1" and running same curl command, an empty reply is returned.

**Comment by marcusolsson** [comment]
Hi, and thanks for submitting an issue on this. Unfortunately, I can't seem to reproduce this. Perhaps a silly question but is it working if you navigate to http://localhost:8081 in the web browser?

**Comment by ctliv** [comment]
Hello. Many thanks for answering. (TL;DR: Solved!!)

No. It is not working in the browser, as well. Chrome returns ERR_EMPTY_RESPONSE.

But I found that the problem may be caused by the docker configuration. Here is a full session:

```
myuser@mypc MINGW64 ~/Dev/workspace/tutorial-environment (master)
$ docker-compose up -d
Creating network "tutorial-environment_grafana" with the default driver
Creating tutorial-environment_promtail_1   ... done
Creating tutorial-environment_db_1         ... done
Creating tutorial-environment_loki_1       ... done
Creating tutorial-environment_grafana_1    ... done
Creating tutorial-environment_app_1        ... done
Creating tutorial-environment_prometheus_1 ... done

myuser@mypc MINGW64 ~/Dev/workspace/tutorial-environment (master)
$ curl http://localhost:8081
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server

myuser@mypc MINGW64 ~/Dev/workspace/tutorial-environment (master)
$ winpty docker exec -it tutorial-environment_app_1 sh
/ # wget http://localhost
Connecting to localhost (127.0.0.1:80)
index.html           100% |*******************************************************************************************************|  4093  0:00:00 ETA
/ #
```

From outside of the container the request to `http://localhost:8081` returns an empty response. But from inside the container (I made a mistake, before) the request to `http://localhost` actually returns a 4093 bytes index.html.

So, I suspect there is something in the docker configuration that prevents container's internal port 80 to be routed to external port 8081. 

I changed port 8081 in port 80:

```
  app:
    build: ./app
    ports:
      - 80:80
    volumes:
      - app_data:/var/log
    networks:
      - grafana
``` 

and now works!!

**Comment by marcusolsson** [comment]
I'm happy to hear! 👍
