### ISSUE TITLE
Docker instructions are out of sync with current plugin generator

### ISSUE THREAD

**Issue by kylehayes** [grafana/tutorials#64]
The CLI for generating a new plugin codebase is using the latest 7.x release but the docker instructions still pull a pre 7.0 release. Changing the docker command to be `docker run -d -p 3000:3000 -v "$(pwd)"/grafana-plugins:/var/lib/grafana/plugins --name=grafana grafana/grafana:7.0.1` resolved my issue.

**Comment by marcusolsson** [comment]
Thank you for the heads-up! 👍
