### ISSUE TITLE
Import \ Definition missing for "baseUrl"

### ISSUE THREAD

**Issue by rniemand** [grafana/tutorials#77]
In the updated `doRequest()` method there is a line that references a const\var **baseUrl** `url: baseUrl + "/metrics"`, however there is no mention of where this value comes from, am I missing something simple here?

**Comment by marcusolsson** [comment]
`baseUrl` would be the base URL of the API endpoint that you're accessing. Would it be more helpful to include a 

```ts
const baseUrl = "https://api.example.com";
```

Or something similar?

**Comment by rniemand** [comment]
> `baseUrl` would be the base URL of the API endpoint that you're accessing. Would it be more helpful to include a
> 
> ```ts
> const baseUrl = "https://api.example.com";
> ```
> 
> Or something similar?

It would help with some confusion here as I was trying to figure out why I could not find a [metrics endpoint](https://grafana.com/docs/grafana/latest/http_api/) in the official documentation 🤦‍♂️

**Comment by marcusolsson** [comment]
Sorry about that 🙏 I'll make sure to add some clarification here! Thanks again!
