### ISSUE TITLE
Grafana fundamentals, requestbin change

### ISSUE THREAD

**Issue by pascalvanmaanen** [grafana/tutorials#80]
LS, 

First, Thx for this Grafana fundamentals labs. I run into one small issue.
When you open the requestbin url, you need to select "Use old version".

https://requestbin.com/

Please take a look to it, to keep this lap up-to-date.

Best regards,

Pascal

**Comment by marcusolsson** [comment]
Thank you! 

I've fixed this in https://github.com/grafana/tutorials/commit/9eee03e79e0c2825b54396621996ae17baf20097
