### ISSUE TITLE
Voting triangle is not visible in grafana-fundamentals tutorial

### ISSUE THREAD

**Issue by jherrera123** [grafana/tutorials#84]
Problem:
Grafana fundamentals tutorial says Grafana News should show a voting triangle next to the link. Voting triangle is not visible.

Link to instructions: https://grafana.com/tutorials/grafana-fundamentals/#2

Steps to reproduce:
- Clone tutorial environment and start with docker-compose
- Go to Grafana news and submit a link
- No voting triangle is visible next to the link

![image](https://user-images.githubusercontent.com/1208947/93691501-11eca480-fab4-11ea-91d6-b3beaeb0f86d.png)

OS: Ubuntu 20.04
Browser: Firefox 80.0.1 (64-bit)

**Comment by jherrera123** [comment]
DNS sinkhole was blocking access to hacker news css file.

**Comment by marcusolsson** [comment]
Thanks for letting us know! 👍
