### ISSUE TITLE
Broken links for landing page

### ISSUE THREAD

**Issue by marcusolsson** [grafana/tutorials#9]
The links that takes you back to the landing page are broken.

- Clicking 'X' icon in the upper left corner of a tutorial
- Clicking the "Done" link at the end of the tutorial

**Comment by noahalorwu** [comment]
I tried solving this issue and this was what I noticed.
After clicking on "Done"  you're returned to the main domain, not the path where the **index** page was placed for the tutorial.
My proposed fix is to create a subdomain **tutorials.grafana.com** linked to the repo Github page.
Here is a [link](http://tut.noahalorwu.com) to try the proposed fix.

**Comment by marcusolsson** [comment]
Thank you for looking into this! We've created a new tutorials site, that should work better in this regard: https://grafana.com/tutorials/
